Ecommerce/ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cartdetail, name='cartdetail'),
    path('add/<int:product_id>/', views.addcart, name='addcart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cartremove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='fullremove')
]

Ecommerce/ecommerce/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoppingcart', include('shoppingcart.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce/ecommerce/search/urls.py
from django.urls import path
from . import views


app_name = 'search'
urlpatterns = [
    path('', views.searchresult, name='searchresult')
]

Ecommerce/ecommerce/shoppingcart/urls.py
from django.urls import path
from . import views

app_name = 'shoppingcart'
urlpatterns = [
    path('', views.allprodcat, name='AllProdCat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodetail, name='procatdet')
]

Ecommerce/ecommerce/cart/models.py
from django.db import models
from shoppingcart.models import Product


# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    qty = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.qty

    def __str__(self):
        return '{}'.format(self.product)

Ecommerce/ecommerce/search/models.py
from django.db import models

# Create your models here.

Ecommerce/ecommerce/shoppingcart/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shoppingcart:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shoppingcart:procatdet', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

Ecommerce/ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shoppingcart.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def cartid(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def addcart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cartid(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=cartid(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.qty < cart_item.product.stock:
            cart_item.qty += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, qty=1, cart=cart)
        cart_item.save()
    return redirect('cart:cartdetail')


def cartdetail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=cartid(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cartitem in cart_items:
            total += (cartitem.product.price * cartitem.qty)
            counter += cartitem.qty
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=cartid(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.qty > 1:
        cart_item.qty -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cartdetail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=cartid(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cartdetail')

Ecommerce/ecommerce/search/views.py
from django.shortcuts import render
from shoppingcart.models import Product
from django.db.models import Q

# Create your views here.


def searchresult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

Ecommerce/ecommerce/shoppingcart/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.


def allprodcat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products})


def prodetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e

    return render(request, 'product.html', {'product': product})

Ecommerce/ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comforter&family=PT+Sans:ital,wght@1,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/bf6856e6ab.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

Ecommerce/ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    ECOM cart
{% endblock %}
{% block title %}
    Your Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Ecom Cart is empty</h1>
        <br>
        <p class="text-center">Buy Now!<a href="{% url 'shoppingcart:AllProdCat' %}"><i class="fas fa-shopping-bag"></i></a></p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Added to Cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for ctitem in cart_items %}
            <tr>
                <td>
                    <a href="ctitem.product.get_absolute_url"><img src="{{ctitem.product.image.url}}" alt="" style="width:70px;height:70px;" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-lef">
                    {{ctitem.product.name}}
                    <br>
                    SKU: {{ctitem.product.id}}
                    <br>
                    Price: ₹{{ctitem.product.price}}
                    <br>
                    Qty: {{ctitem.qty}} x ₹{{ctitem.product.name}}
                </td>
                <td>
                    ₹{{ctitem.sub_total}}
                </td>
                {% if ctitem.qty < ctitem.product.stock %}
                <td>
                    <a href="{% url 'cart:addcart' ctitem.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cartremove' ctitem.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:fullremove' ctitem.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                 <td>
                     &nbsp;<a href="{% url 'cart:cartremove' ctitem.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                     &nbsp;<a href="{% url 'cart:fullremove' ctitem.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your items before checking out
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Cart subtotal ({{item_count}} item): <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shoppingcart:AllProdCat' %}" class="btn btn-secondary btn-block my_custom_button"><i class="fas fa-shopping-bag"></i></a>
            <a href="" class="btn btn-warning btn-block my_custom_button">Proceed to Buy</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock%}

Ecommerce/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to Ecom shopping!
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} - Ecom Store
    {% else %}
        Ecom Shopping.
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a class="btn btn-secondary" href="{% url 'shoppingcart:AllProdCat' %}">Our Product Collection</a> </p>
            </div>
        </div>
    </div>
{% endif %}
{% if category %}
    <div class="mx-auto">
        <img class="my_image" src="{{category.image.url}}" width="1296px" alt="{{category.name}}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
{% else %}
    <div>
        <img class="my_image" src="{% static 'img/banner.png' %}" alt="our products" width="1296px">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">Our Product Collections</h1>
        <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    </div>
{% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" width="150px" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

Ecommerce/ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">Copyright © 2012 The Ecom Shopping Store</p>
</div>

Ecommerce/ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shoppingcart:AllProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage" width="150px"></a>
    </center>
</header>

Ecommerce/ecommerce/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shoppingcart:AllProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shoppingcart' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shoppingcart:AllProdCat' %}">All Products</a></li>
            {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cartdetail' %}"><i class="fas fa-cart-arrow-down"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search:searchresult' %}" method="get">{% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

Ecommerce/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if product %}
        {{ product.name }} - Ecom Store
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shoppingcart:AllProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
     <div class="col-12 col-sm-12 col-md-12 col-lg-6">
         <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>₹{{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:addcart' product.id %}">Add to Cart</a>
            {% endif %}
         </div>
     </div>
</div>

{% endblock %}

Ecommerce/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Search your products here.
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" width="150px" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}